[package]
name = "manifester"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]
edition = "2018"

[dependencies]
image = "0.20"
serde = "1.0"
serde_json ="1.0"
globwalk = "0.5"
failure = "0.1"
hashbrown = "0.1"
